im : "test" # im-kayac user name

feeds :
- "http://search.twitter.com/search.atom?q=shokai"
- "http://pcod.no-ip.org/yats/search?query=shokai&lang=ja&rss"

filters : 
- "_shokai"
- "shokai_"

#debug : "true"
